In [1]:
# blast gene hits
# concat the gene hits to different genomes

In [6]:
%pwd

'/Volumes/SBGE/michael/16_genomes/unique_orfs/nb'

In [11]:
%ls ../data/blast_genes-hits/MEL1/
%ls ../data/blast_gene-hits/MEL1/

MSY24.tsv*     MSY28.tsv*     MSY32.tsv*     MSY36.tsv*     s288c-orf.tsv*
MSY25.tsv*     MSY29.tsv*     MSY33.tsv*     MSY37.tsv*
MSY26.tsv*     MSY30.tsv*     MSY34.tsv*     MSY38.tsv*
MSY27.tsv*     MSY31.tsv*     MSY35.tsv*     MSY39.tsv*

In [12]:
%ls ../data/blast_gene-hits/MEL1/

ls: ../data/blast_gene-hits/MEL1/: No such file or directory

In [24]:
import pandas as pd
import numpy as np

In [53]:
#ref = 's288c-orf'
genes = ['MEL1','XDH1','MAL11','MAL12','MAL13','MAL31','MAL32','MAL33','OPT2','SGE1','SUC2']
genomes = ['MSY24','MSY25','MSY26','MSY27','MSY28','MSY29','MSY30','MSY31','MSY32','MSY33','MSY34','MSY35','MSY36','MSY37','MSY38','MSY39']
blast_cols=['query','hit','percent_id','length','mismatch','gapopen','qstart','qend','tstart','tend','evalue','bitscore']
df_cols = ['strain','header','s288c_hit','percent_id']

In [54]:
# iterate through each df and add 
df_list = []

for gene in genes:
    for genome in genomes:
        df = pd.read_csv(f'../data/blast_gene-hits/{gene}/{genome}.tsv', sep='\t', names=blast_cols)
        df['hit_strain'] = genome
        df_list.append(df)
df = pd.concat(df_list)
df.reset_index(inplace=True, drop=True)

df['hit_start'] = df.hit.str.split(':').str[1]
df['hit_end'] = df.hit.str.split(':').str[2].str.split(' ').str[0]
df['hit_name'] = df.hit.str.split(r"_").str[0].str[4:]
#df['hit_name'] = df.hit.str.split('_').str[1] + "_" + df['hit_name']
df['hit_chr'] = df.hit.str.split('_').str[2].str.split(':').str[0]
df['hit_strand'] = np.where(df.hit_start < df.hit_end, '+','-')

In [55]:
df

,query,hit,percent_id,length,mismatch,gapopen,qstart,qend,tstart,tend,evalue,bitscore,hit_strain,hit_start,hit_end,hit_name,hit_chr,hit_strand
0,MEL1,lcl|ORF1641_MSY24_chrIV:1032810:1032508,28.358,67,38,2,60,116,28,94,0.570000,29.3,MSY24,1032810,1032508,ORF1641,chrIV,-
1,MEL1,lcl|ORF328_MSY24_chrVII:274444:274710,40.000,40,21,3,186,223,4,42,1.700000,27.7,MSY24,274444,274710,ORF328,chrVII,+
2,MEL1,lcl|ORF360_MSY24_chrXIII:549688:550407,34.375,32,21,0,368,399,125,156,3.500000,28.1,MSY24,549688,550407,ORF360,chrXIII,+
3,MEL1,lcl|ORF1610_MSY24_chrVII:137287:136982,26.744,86,60,2,363,448,18,100,9.400000,25.8,MSY24,137287,136982,ORF1610,chrVII,-
4,MEL1,lcl|ORF1283_MSY25_chrIV:1065003:1064701,28.358,67,38,2,60,116,28,94,0.590000,29.3,MSY25,1065003,1064701,ORF1283,chrIV,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5089,SUC2,lcl|ORF73_MSY38_chrXVI:264663:267377,35.000,40,26,0,244,283,496,535,4.100000,28.5,MSY38,264663,267377,ORF73,chrXVI,+
5090,SUC2,lcl|ORF124_MSY39_chrIX:33493:35265,99.624,532,2,0,1,532,59,590,0.000000,1093.0,MSY39,33493,35265,ORF124,chrIX,+
5091,SUC2,lcl|ORF1045_MSY39_chrXVI:342872:341040,27.155,232,135,11,252,471,237,446,0.000055,44.3,MSY39,342872,341040,ORF1045,chrXVI,-
5092,SUC2,lcl|ORF938_MSY39_chrXII:400425:399736,29.231,65,45,1,329,393,119,182,3.600000,28.1,MSY39,400425,399736,ORF938,chrXII,-
5093,SUC2,lcl|ORF277_MSY39_chrXVI:263320:266034,35.000,40,26,0,244,283,496,535,4.300000,28.5,MSY39,263320,266034,ORF277,chrXVI,+

In [56]:
cols = ['query','hit_strain','hit_chr','hit_name','start','end','strand','aa_seq']
df.to_csv('../data/blast_gene-hits/gene_hits.csv', index=False)